modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="spore_performance"
version="${file.jarVersion}"
displayName="Spore Performance"
authors="ARXYT"
description='''Performance and compatibility optimisations for Spore 2.2.0j.'''

[[dependencies.spore_performance]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.spore_performance]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.spore_performance]]
modId="spore"
mandatory=true
versionRange="[2.2.0j,2.3)"
ordering="AFTER"
side="BOTH"

[[dependencies.spore_performance]]
modId="exhuashan_sporeai_fix"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.spore_performance]]
modId="sporesrp"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.spore_performance]]
modId="embeddium"
mandatory=false
versionRange="[0.3.31,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.spore_performance]]
modId="acceleratedrendering"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.spore_performance]]
modId="sona"
mandatory=false
versionRange="[1.5.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.spore_performance]]
modId="touhoulittlemaid"
mandatory=false
versionRange="[1.5.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.spore_performance]]
modId="tacz"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
